services:
  - type: web
    name: crt-evolution-mt5
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: MT5_LOGIN
        value: 91033361
      - key: MT5_PASSWORD
        value: wcWapaD4
      - key: MT5_SERVER
        value: LiteFinance-MT5-Demo
      - key: EA_INITIAL_LOT
        value: 0.01
      - key: EA_STEP_DOLLARS
        value: 10.0
      - key: EA_MAX_LOT
        value: 10.0
      - key: EA_SL_POINTS
        value: 110
      - key: EA_TP_MULTIPLIER
        value: 5
      - key: EA_NY_START
        value: 8
      - key: EA_NY_END
        value: 22
      - key: EA_MAGIC
        value: 240226
    autoDeploy: true
